---
settings:
  name: BlueXP replication
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: fr-fr,us-en,de-de,es-es,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documents de réplication BlueXP
    url: "/index.html"
  - title: Notes de mise à jour
    entries:
    - title: Quoi de neuf
      url: "/whats-new.html"
  - title: Commencez
    entries:
    - title: Découvrez la réplication BlueXP
      url: "/concept-replication.html"
    - title: Configurez la solution de réplication des données
      url: "/task-replicating-data.html"
  - title: Gérez la réplication des données
    url: "/task-managing-replication.html"
  - title: En savoir plus >>
    entries:
    - title: En savoir plus sur les règles de réplication
      url: "/concept-replication-policies.html"
    - title: En savoir plus sur les stratégies de sauvegarde
      url: "/concept-backup-policies.html"
  - title: Connaissances et support
    entries:
    - title: S'inscrire pour obtenir de l'aide
      url: "/task-support-registration.html"
    - title: Obtenez de l'aide
      url: "/task-get-help.html"
  - title: Mentions légales
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
